CREATE TABLE IF NOT EXISTS friends(
    user_friend_id int generated by default as identity primary key,
    is_confirmed boolean
    );

CREATE table IF NOT EXISTS users(
    user_id int generated by default as identity primary key,
    email varchar NOT NULL,
    login varchar NOT NULL,
    name varchar,
    birthday date,
    friends int REFERENCES friends (user_friend_id)
    );

ALTER TABLE friends ADD COLUMN IF NOT EXISTS friend_id int REFERENCES users (user_id);

CREATE TABLE IF NOT EXISTS likes(
    film_user_id int generated by default as identity primary key,
    user_id int REFERENCES users (user_id)
    );

CREATE TABLE IF NOT EXISTS genres(
    film_genres_id int generated by default as identity primary key,
    name varchar
    );

CREATE TABLE IF NOT EXISTS films(
    film_id int generated by default as identity primary key,
    name varchar NOT NULL,
    description varchar(200),
    releaseDate date NOT NULL,
    duration int,
    rating varchar,
    likes int REFERENCES likes (film_user_id),
    genres int REFERENCES genres (film_genres_id)
    );

--DROP TABLE IF EXISTS FILMS, FRIENDS, GENRES, LIKES, USERS;